import Head from 'next/head'
import Footer from '../components/Footer';
import dynamic from 'next/dynamic';
import React from "react";
import { FaTwitter, FaGithub, FaYoutube } from "react-icons/fa";

const Header = dynamic(() => import('../components/Header'), {
  ssr: false,
})

export default function Home() {
  return (
    <div className="min-h-screen bg-base-200" data-theme="bumblebee">
      <Head>
        <title>Let's Mint Some NFTs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />


      <div class="bg-white dark:bg-gray-800 overflow-hidden relative lg:flex lg:items-center h-screen p-10">
        <div class="w-full py-12 px-4 sm:px-6 lg:py-16 lg:px-8 z-20">
          <h2 class="text-3xl font-extrabold text-black dark:text-white sm:text-4xl">
            <span class="block">
              Mother hearth host your travel
            </span>
          </h2>
          <p class="text-md mt-4 text-gray-400">
            The state of Utah in the united states is home to lots of beautiful National parks.
          </p>
          <div class="lg:mt-0 lg:flex-shrink-0">
            <div class="mt-12 inline-flex">
              <button type="button" className="btn btn-primary ml-3 normal-case p-3">
                Free Mint
              </button>
            </div>
          </div>
        </div>

        <div class="grid grid-rows-3 grid-flow-col gap-8">
          <div><img src="/images/4-1.jpg" className="mx-auto object-cover rounded-xl w-30"></img></div>
          <div><img src="/images/4-1.jpg" className="mx-auto object-cover rounded-xl w-30"></img></div>
          <div><img src="/images/4-1.jpg" className="mx-auto object-cover rounded-xl w-30"></img></div>
          <div><img src="/images/4-1.jpg" className="mx-auto object-cover rounded-xl w-30"></img></div>
          <div><img src="/images/4-1.jpg" className="mx-auto object-cover rounded-xl w-30"></img></div>
          <div><img src="/images/4-1.jpg" className="mx-auto object-cover rounded-xl w-30"></img></div>
          <div><img src="/images/4-1.jpg" className="mx-auto object-cover rounded-xl w-30"></img></div>
          <div><img src="/images/4-1.jpg" className="mx-auto object-cover rounded-xl w-30"></img></div>
          <div><img src="/images/4-1.jpg" className="mx-auto object-cover rounded-xl w-30"></img></div>
          <div><img src="/images/4-1.jpg" className="mx-auto object-cover rounded-xl w-30"></img></div>
          <div><img src="/images/4-1.jpg" className="mx-auto object-cover rounded-xl w-30"></img></div>
          <div><img src="/images/4-1.jpg" className="mx-auto object-cover rounded-xl w-30"></img></div>
        </div>
      </div>


      <div class="p-8 bg-white dark:bg-gray-800  shadow">
        <p class="text-center text-3xl font-bold text-gray-800 dark:text-white">
          Professional team
        </p>
        <p class="text-center mb-12 text-xl font-normal text-gray-500 dark:text-gray-200">
          Meat the best team in wolrd
        </p>
        <div class="flex flex-col justify-center md:flex-row evenly m-auto">
          <div className="">
            <div class="text-center mb-4 opacity-90">
              <a href="#" class="block relative">
                <img alt="profil" src="/images/1.jpg" class="mx-auto object-cover rounded-full h-40 w-40 " />
              </a>
            </div>
            <div class="text-center">
              <p class="text-2xl text-gray-800 dark:text-white">
                Patrick Sebastien
              </p>
              <p class="text-xl text-gray-500 dark:text-gray-200 font-light">
                Developpeur
              </p>
              <p class="text-md text-gray-500 dark:text-gray-400 max-w-xs py-4 font-light">
                Patrick Sébastien, born November 14, 1953 in Brive-la-Gaillarde, is an imitator.
              </p>
            </div>
            <div class="pt-8 flex border-t border-gray-200 w-44 mx-auto text-gray-500 items-center justify-between">

            </div>
          </div>
          <div className="">
            <div class="text-center mb-4 opacity-90">
              <a href="#" class="block relative">
                <img alt="profil" src="/images/4-1.jpg" class="mx-auto object-cover rounded-full h-40 w-40 " />
              </a>
            </div>
            <div class="text-center">
              <p class="text-2xl text-gray-800 dark:text-white">
                Jean Castux
              </p>
              <p class="text-xl text-gray-500 dark:text-gray-200 font-light">
                Founder
              </p>
              <p class="text-md text-gray-500 dark:text-gray-400 max-w-xs py-4 font-light">
                Jean Castux is an imitator, humorist, actor, born November 14, 1953 in Pontivy.
              </p>
            </div>
            <div class="pt-8 flex border-t border-gray-200 w-44 mx-auto text-gray-500 items-center justify-between">

            </div>
          </div>


          <div className="">
            <div class="text-center mb-4 opacity-90">
              <a href="#" class="block relative">
                <img alt="profil" src="/images/4-1.jpg" class="mx-auto object-cover rounded-full h-40 w-40 " />
              </a>
            </div>
            <div class="text-center">
              <p class="text-2xl text-gray-800 dark:text-white">
                Jean Castux
              </p>
              <p class="text-xl text-gray-500 dark:text-gray-200 font-light">
                Market
              </p>
              <p class="text-md text-gray-500 dark:text-gray-400 max-w-xs py-4 font-light">
                Jean Castux is an imitator, humorist, actor, born November 14, 1953 in Pontivy.
              </p>
            </div>
            <div class="pt-8 flex border-t border-gray-200 w-44 mx-auto text-gray-500 items-center justify-between">

            </div>
          </div>

        </div>
      </div>


      <div class="pt-10 p-8 bg-white dark:bg-gray-800  shadow">
        <p class="text-center text-3xl font-bold text-gray-800 dark:text-white">
          Join Our Community
        </p>
        <div class="flex flex-col justify-center md:flex-row evenly gap-x-10">
          <div class="p-4 mt-20">
            <div class="text-center mb-4 opacity-90">
              <FaTwitter size="7rem" /> TWITTER
            </div>

          </div>
          <div class="p-4 mt-20">
            <div class="text-center mb-4 opacity-90">
              <FaGithub size="7rem" /> GITHUB
            </div>
          </div>


          <div class="p-4 mt-20">
            <div class="text-center mb-4 opacity-90">
              <FaYoutube size="7rem" />YOUTUBE
            </div>
          </div>

        </div>
      </div>


      <Footer />
    </div >
  )
}
